### ISSUE TITLE
2 GRAV REPOS !!!!

### ISSUE THREAD

**Issue by frju365** [lithrel/grav_ynh#2]
There are 2 grav_ynh repos for one app. I think you need to contact @magikcypress to have the same repos with the commits of all repos. A mail contact will be fine too. I added you to the grav Team to have a better team work.

**Comment by frju365** [comment]
Once you agree to create a new repos with all the commit I will add this repos to the team.

**Comment by magikcypress** [comment]
@lithrel Contact me on my email or on XMPP_FR conference.yunohost.org -> Apps

**Comment by lithrel** [comment]
Hey !
I never realized there was another grav package, sorry about that. I had a few more things in mind to implement before proposing it to the list, and I'd like to get a good score on package_check (but I kind of crashed my dev env yesterday running it). I'm also wondering what is the best choice between including grav sources in the package or pulling it from the official repo.
Anyway, I'll be on the Apps chan all day :)

<sup>Caps lock and exclamation marks, I like your energy, what's your coffee brand ?</sup>

**Comment by magikcypress** [comment]
Hi,
You watched to push a PR for README?

**Comment by frju365** [comment]
You have, you two, write access on `Yunohost-Apps/grav_ynh`. So please, lithrel, can you do a PR and ask for the approval of cyp, then you merge it(or you merge it directly) ?

**Comment by magikcypress** [comment]
I push a PR for this beautiful README ;)

here: https://github.com/YunoHost-Apps/grav_ynh/pull/2

**Comment by frju365** [comment]
Long time this problem is fixed. Thanks.
